// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/data/repositories/loan_application_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobile/data/datasources/loan_application_datasource.dart'
    as _i2;
import 'package:mobile/domain/entities/loan_application.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoanApplicationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoanApplicationDataSource extends _i1.Mock
    implements _i2.LoanApplicationDataSource {
  MockLoanApplicationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.LoanApplication>> getAllApplications(
    String? microfinancieraId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllApplications, [microfinancieraId]),
            returnValue: _i3.Future<List<_i4.LoanApplication>>.value(
              <_i4.LoanApplication>[],
            ),
          )
          as _i3.Future<List<_i4.LoanApplication>>);

  @override
  _i3.Future<List<_i4.LoanApplication>> getAssignedToAgent(
    String? microfinancieraId,
    String? agentId, {
    List<String>? statusFilter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getAssignedToAgent,
              [microfinancieraId, agentId],
              {#statusFilter: statusFilter},
            ),
            returnValue: _i3.Future<List<_i4.LoanApplication>>.value(
              <_i4.LoanApplication>[],
            ),
          )
          as _i3.Future<List<_i4.LoanApplication>>);

  @override
  _i3.Future<List<_i4.LoanApplication>> getApplicationsByStatus(
    String? microfinancieraId,
    List<String>? statuses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getApplicationsByStatus, [
              microfinancieraId,
              statuses,
            ]),
            returnValue: _i3.Future<List<_i4.LoanApplication>>.value(
              <_i4.LoanApplication>[],
            ),
          )
          as _i3.Future<List<_i4.LoanApplication>>);

  @override
  _i3.Future<_i4.LoanApplication?> getApplicationById(
    String? microfinancieraId,
    String? applicationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getApplicationById, [
              microfinancieraId,
              applicationId,
            ]),
            returnValue: _i3.Future<_i4.LoanApplication?>.value(),
          )
          as _i3.Future<_i4.LoanApplication?>);

  @override
  _i3.Future<void> takeOwnership(
    String? microfinancieraId,
    String? applicationId,
    String? agentId,
    String? agentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#takeOwnership, [
              microfinancieraId,
              applicationId,
              agentId,
              agentUserId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateApplicationStatus(
    String? microfinancieraId,
    String? applicationId,
    String? newStatus,
    String? userId, {
    String? reason,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateApplicationStatus,
              [microfinancieraId, applicationId, newStatus, userId],
              {#reason: reason, #additionalData: additionalData},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.LoanApplication>> watchAssignedApplications(
    String? microfinancieraId,
    String? agentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchAssignedApplications, [
              microfinancieraId,
              agentId,
            ]),
            returnValue: _i3.Stream<List<_i4.LoanApplication>>.empty(),
          )
          as _i3.Stream<List<_i4.LoanApplication>>);

  @override
  _i3.Stream<List<_i4.LoanApplication>> watchApplicationsByStatus(
    String? microfinancieraId,
    List<String>? statuses,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchApplicationsByStatus, [
              microfinancieraId,
              statuses,
            ]),
            returnValue: _i3.Stream<List<_i4.LoanApplication>>.empty(),
          )
          as _i3.Stream<List<_i4.LoanApplication>>);

  @override
  _i3.Future<Map<String, int>> getApplicationStats(String? microfinancieraId) =>
      (super.noSuchMethod(
            Invocation.method(#getApplicationStats, [microfinancieraId]),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<Map<String, int>> getAgentStats(
    String? microfinancieraId,
    String? agentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAgentStats, [microfinancieraId, agentId]),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);
}
