// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWNjLtw13CW-FmFa5nCMqtfrbi6sEI6KE',
    appId: '1:862824702457:web:41b141c736ff11b6005d28',
    messagingSenderId: '862824702457',
    projectId: 'microfinance-3753e',
    authDomain: 'microfinance-3753e.firebaseapp.com',
    storageBucket: 'microfinance-3753e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKrPTG_bFJZfSCr6TFrFgZSI7TEdk35Ug',
    appId: '1:862824702457:android:cd5bd172f5544920005d28',
    messagingSenderId: '862824702457',
    projectId: 'microfinance-3753e',
    storageBucket: 'microfinance-3753e.firebasestorage.app',
    androidClientId:
        '862824702457-1faki5bgf2sblhiauqfis1sncga2el23.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9No4ZrQG8BF122mHClDgYVc0pbJ370YA',
    appId: '1:862824702457:ios:8f8c756e32f776e1005d28',
    messagingSenderId: '862824702457',
    projectId: 'microfinance-3753e',
    storageBucket: 'microfinance-3753e.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
    iosClientId:
        '862824702457-nmeks60f1ftn8umv11n8arevshj2klsf.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9No4ZrQG8BF122mHClDgYVc0pbJ370YA',
    appId: '1:862824702457:ios:8f8c756e32f776e1005d28',
    messagingSenderId: '862824702457',
    projectId: 'microfinance-3753e',
    storageBucket: 'microfinance-3753e.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
    iosClientId:
        '862824702457-nmeks60f1ftn8umv11n8arevshj2klsf.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWNjLtw13CW-FmFa5nCMqtfrbi6sEI6KE',
    appId: '1:862824702457:web:7c53229dace89a5d005d28',
    messagingSenderId: '862824702457',
    projectId: 'microfinance-3753e',
    authDomain: 'microfinance-3753e.firebaseapp.com',
    storageBucket: 'microfinance-3753e.firebasestorage.app',
  );
}
